Eschool/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from core.views import error_404
from django.conf import settings
from django.conf.urls.static import  static

urlpatterns = [
    path('', include('core.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('class/', include('class.urls')),
    path('forum/', include('forum.urls')),
    path('notification/', include('notification.urls')),
    path(r'tests/', include('quiz.urls')),
]

# handler404 = error_404
# handler500 = error_404
urlpatterns += static(settings.STATIC_URL,
                      document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.STATIC_URL,
                      document_root=settings.STATICFILES_DIRS)
urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)
if settings.DEBUG == False:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT) 
    urlpatterns += static(settings.STATIC_URL,
                      document_root=settings.STATICFILES_DIRS)

class/urls.py
from django.urls import path

app_name = 'class'

from .views import *
urlpatterns = [
    path('', index, name='index'),
    path('<slug>/', index),
    path('viewClass/<slug>/', viewClass, name='viewClass'),
    path(r'search/', search, name='search'),
]

core/urls.py
from django.urls import path
from .views import *

app_name = 'core'

urlpatterns = [
    path('', index, name='index'),
    path('profile/', profile, name='profile'),
    path('profile/Submit/', ProfileFormValidator, name='ProfileFormValidator'),
    path('manual/', manual, name='manual'),
    path('report-bug/', reportBug, name='reportBug'),
    path('add/bug', addBugsForm, name='addBugsForm'),
]

forum/urls.py
from django.urls import path
from .views import *

app_name = 'forum'

urlpatterns = [
    path('', index, name='index'),
    path('sendMSG/', addForumForm, name='addForumForm'),
]

notification/urls.py
from django.urls import path
from .views import *

app_name = 'notification'

urlpatterns = [
    path('', index, name='index'),
    path('createNotification/', addNotification, name='addNotification'),
    path('add/', addNotificationForm, name='addNotificationForm'),
]

forum/models.py
from django.conf import settings
from django.db import models
from django.shortcuts import reverse
from django.utils import timezone

class Forum(models.Model):
	user = models.CharField(max_length=100)
	message = models.CharField(max_length=10000)
	date = models.DateTimeField(auto_now_add=True)

notification/models.py
from django.conf import settings
from django.db import models
from django.shortcuts import reverse
from django.utils import timezone
PRIORITY_CHOICES = (
		('danger', ('Top Priority')),
		('warning', ('Middle Priority')),
		('success', ('Minor Priority')),
		('dark', ('Other')),
	)
class Notification(models.Model):
	user = models.CharField(max_length=100)
	message = models.CharField(max_length=100)
	priority = models.CharField(choices=PRIORITY_CHOICES, max_length=100)
	duration = models.IntegerField()
	dontDisplay = models.BooleanField(default=False)
	date = models.DateTimeField(auto_now_add=True)

forum/forms.py
from django import forms

from .models import *

class ForumForm(forms.ModelForm):
    class Meta:
        model = Forum
        fields = ('message','user')

notification/forms.py
from django import forms
from .models import *

class NotificationForm(forms.ModelForm):
    class Meta:
        model = Notification
        fields = ('user', 'message', 'duration', 'priority')

forum/views.py
from django.contrib import messages
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from django.views.generic import DetailView, ListView, View
from django.conf import settings
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


from core.models import *
from core.forms import *

from .models import *
from .forms import *
		
# Create your views here.
@login_required
def index(request):
	try:
		profileData = Profile.objects.get(displayName=request.user)
	except ObjectDoesNotExist:
		profileData = []
		messages.info(request, "Please Create a Profile")
	username = str(request.user)
	forumData = Forum.objects.all().order_by("-id")
	forumDataReverse = forumData.reverse()
	#request for page query
	page = request.GET.get('page')
	#paginate by 30 messages
	paginator = Paginator(forumDataReverse, 3)
	try:
		forumDataReverse = paginator.page(page)
	except PageNotAnInteger:
		forumDataReverse = paginator.page(1)
	except EmptyPage:
		posts = paginator.page(paginator.num_pages)

	context = {
		'profileData': profileData,
		'username': username,
		'forumData': forumDataReverse,
		'forumForm': ForumForm,
		'title': 'Forum',
		'pages': paginator.num_pages,
	}
	return render(request, "forum.html", context)

@login_required
def addForumForm(request):
    if request.method == 'POST':
        form = ForumForm(request.POST)
        if form.is_valid():
            form.save()
        else:
        	messages.error(request, "Please Fill All The Fields")
    else:
    	messages.error(request, "Something Went Wrong")
    return redirect('forum:index')

notification/views.py
from django.contrib import messages
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from django.views.generic import DetailView, ListView, View
from django.conf import settings
from django.core.files.storage import FileSystemStorage

import datetime

from core.models import *
from core.forms import *

from .models import *
from .forms import *
def hideNotification():
	notificationData = Notification.objects.filter(dontDisplay=False).order_by("-id")
	for notifications in notificationData:
		currentDate = datetime.date.today()
		dateUploaded = f"{notifications.date.month}/{notifications.date.day}/{notifications.date.year}"
		convertDateUploaded = datetime.datetime.strptime(dateUploaded, '%m/%d/%Y').date()
		duration = currentDate - convertDateUploaded
		strDuration = str(duration)
		if duration.days >= notifications.duration:
			notifications.dontDisplay = True
			notifications.save()
			

@login_required 
def index(request):
	hideNotification()
	notificationData = Notification.objects.filter(dontDisplay=False).order_by("-id")
	try:
		profileData = Profile.objects.get(displayName=request.user)
	except ObjectDoesNotExist:
		profileData = []
		messages.info(request, "Please Create a Profile")
	context = {
		'title': 'Notifications',
		'profileData': profileData,
		'notificationData': notificationData,
	}
	return render(request, "notification.html", context) 

@staff_member_required 
def addNotification(request):
	try:
		profileData = Profile.objects.get(displayName=request.user)
	except ObjectDoesNotExist:
		profileData = []
		messages.info(request, "Please Create a Profile")
	context = {
		'title': 'Create Notification',
		'profileData': profileData,
		'notificationForm': NotificationForm,
	}
	return render(request, "create-notification.html", context) 
@staff_member_required
def addNotificationForm(request):
    if request.method == 'POST':
        form = NotificationForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
        else:
        	messages.error(request, "Please Fill All The Fields")
    else:
    	messages.error(request, "Something Went Wrong")
    return redirect('notification:index')

templates/class.html
{% extends 'blank.html' %}
{% load static %}
{% block content  %}
<link href="{% static 'vendor/datatables/dataTables.bootstrap4.min.css' %}" rel="stylesheet">
  <!-- Page Heading -->
  <div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">{{ title }}</h1>
    <a href="#" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i class="fab fa-chart fa-sm text-white-50"></i> Students Rating</a>
  </div>

  <!-- Content Row -->
  <div class="row">
    <div class="col-md-12">
      <div class="card-body">
        <div class="mx-auto d-block">
          <div class="card shadow mb-4">
            <div class="card-header py-3">
              <h6 class="m-0 font-weight-bold text-primary">{{ title.title }}</h6>
            </div>
            <div class="card-body">
              <div class="table-responsive">
                <div id="dataTable_wrapper" class="dataTables_wrapper dt-bootstrap4">
                  <div class="row">
                    <div class="col-sm-12">
                      <table class="table table-bordered dataTable" id="dataTable" width="100%" cellspacing="0" role="grid" aria-describedby="dataTable_info" style="width: 100%;">
                        <thead>
                          <tr role="row">
                            <th class="sorting_asc" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Name: activate to sort column descending" style="width: 160px;">
                             #
                            </th>
                            <th class="sorting_asc" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Name: activate to sort column descending" style="width: 160px;">
                             Teacher Name
                            </th>
                            <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-label="Office: activate to sort column ascending" style="width: 115px;">
                              Subject
                            </th>
                            <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-label="Position: activate to sort column ascending" style="width: 244px;">
                              Topic
                            </th>
                            <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-label="Age: activate to sort column ascending" style="width: 50px;">
                              Date
                            </th>
                          </tr>
                        </thead>
                        <tfoot>
                          <tr>
                            <th rowspan="1" colspan="1">#</th>
                            <th rowspan="1" colspan="1">Teacher Name</th>
                            <th rowspan="1" colspan="1">Subject</th>
                            <th rowspan="1" colspan="1">Topic</th>
                            <th rowspan="1" colspan="1">Date</th>
                          </tr>
                        </tfoot>
                        <tbody>
                          {%for content in classes.all %}
                            <tr role="row" class="odd">
                                <td class="sorting_1">{{ forloop.counter }}</td>
                                <td>{{ content.teacher_name.title }}</td>
                                <td>{{ content.subject.title }}</td>
                                <td><a href="{% url 'class:index' %}viewClass/{{ content.id }}">{{ content.topic.title }}</a></td>
                                <td>{{ content.date }}</td>
                            </tr>
                          {% empty%}
                            <tr>
                                <td colspan='5'>No Available Class Now</td>
                            </tr>
                          {% endfor %}
                        </tbody>
                      </table>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- Custom scripts for all pages-->

  <!-- Page level plugins -->
  <script src="{% static 'vendor/datatables/jquery.dataTables.min.js' %}"></script>
  <script src="{% static 'vendor/datatables/dataTables.bootstrap4.min.js' %}"></script>

  <!-- Page level custom scripts -->
  <script src="{% static 'js/demo/datatables-demo.js' %}"></script>
{% endblock %}

templates/create-notification.html
{% extends 'blank.html' %}
{% load static %}
{% block content  %}
{% load crispy_forms_tags %}

  <!-- Page Heading -->
  <div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">{{ title }}</h1>
    <a href="#" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i class="fab fa-chart fa-sm text-white-50"></i> Students Rating</a>
  </div>
  <!-- Content Row -->

  <div class="row">

    <!-- Content -->
    <div class="col-xl-8 mx-auto col-lg-7">
      <div class="card shadow mb-4">
        <form method="post"  class="m-5" action="{% url 'notification:addNotificationForm' %}">
          {% csrf_token %}
          {{ notificationForm | crispy }}
          <button class="btn btn-block btn-primary" type="submit">Create</button>
        </form>
      </div>
    </div>
  </div>

  <script type="text/javascript">
            userInputField = document.getElementById('id_user')
            userInputField.value = '{{ request.user }}'
            userInputField.style.display = 'none'
            document.getElementById('div_id_user').style.display = 'none'
  </script>
  <!-- Custom scripts for all pages-->
{% endblock %}

templates/forum.html
{% extends 'blank.html' %}
{% load static %}
{% block content  %}
{% load crispy_forms_tags %}
  <!-- Page Heading -->
  <div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">{{ title }}</h1>
    <a href="#" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i class="fab fa-chart fa-sm text-white-50"></i> Students Rating</a>
  </div>

  <!-- Content Row -->

  <!-- Content Row -->

  <div class="row">
    <div class="col-md-10 mx-auto">
      <div class="card">
        <div class="card-header">
          <p class="card-title">{{ title.title }}</p>
        </div>
        <div class="card-body">
          <div class="msg_history">
          {% for messages in forumData %}
            {% if username.title == messages.user.title %}
              <div class="outgoing_msg">
                <div class="sent_msg">
                  <p>{{ messages.message}}</p>
                  <span class="time_date">{{ messages.user.title }} | {{ messages.date.time }}    |    {{ messages.date.day }} / {{ messages.date.month }} / {{ messages.date.year }}</span> </div>
              </div>
            {% else %}
              <div class="incoming_msg mb-3">
                <div class="incoming_msg_img"> 
                  <img src="https://ptetutorials.com/images/user-profile.png" alt="sunil">
                </div>
                <div class="received_msg">
                  <div class="received_withd_msg">
                    <p>{{ messages.message}}</p>
                    <span class="time_date"> 
                      {{ messages.user.title }} | {{ messages.date.time }}    |    {{ messages.date.day }} / {{ messages.date.month }} / {{ messages.date.year }}
                    </span>
                  </div>
                </div>
              </div>

            {% endif %}
           
          {% empty %}
            <div class="outgoing_msg">
                <div class="sent_msg">
                  <p><strong>Empty Chat</strong></p>
                  <span class="time_date">
                    <script type="text/javascript">
                      document.write(date())
                    </script>
                  </span>
                </div>
              </div>
          {% endfor %}
          </div>
        </div>
        <nav class="blog-pagination justify-content-center d-flex">
          <ul class="pagination">
              {% if forumData.has_previous %}
                  <li class="page-item">
                      <a title="Recent Messages" href="?page={{ forumData.previous_page_number }}" class="page-link" aria-label="Recent Messages">
                          Older Messages
                      </a>
                  </li>

              {% else %}
              {% endif %}
              {% if forumData.has_next %}
                  <li class="page-item">
                      <a title="Older Messages" href="?page={{ forumData.next_page_number }}" class="page-link" aria-label="Next">
                          Recent Messages
                      </a>
                  </li>
              {% else %}
              {% endif %}
              <li class="page-item">
                      <a title="Older Messages" href="?page={{ pages }}" class="page-link" aria-label="Next">
                          Most Recent Messages
                      </a>
                  </li>
          </ul>
        </nav>
        <div class="type_msg">
          <div class="input_msg_write">
          <form action="{% url 'forum:addForumForm' %}" method="POST">
            {% csrf_token %}
            {{ forumForm.user }}        
            {{ forumForm.message }}        
            <button style="height: 100%;top: 0px;width: 85px;border-radius: 0px; " class="msg_send_btn" type="submit">Send</button>
          </form>
          <script type="text/javascript">
            userInputField = document.getElementById('id_user')
            userInputField.value = '{{ username }}'
            userInputField.style.display = 'none'
          </script>
          </div>
        </div>
      </div>
    </div>
  </div>

  <link href="{% static 'css/chat.css' %}" rel="stylesheet">

{% endblock %}

templates/notification.html
{% extends 'blank.html' %}
{% load static %}
{% block content  %}
  <!-- Page Heading -->
  <div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">{{ title }}</h1>
    <a href="#" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i class="fab fa-chart fa-sm text-white-50"></i> Students Rating</a>
  </div>

  <!-- Content Row -->

  <div class="row">

    <!-- Content -->
    <div class="col-xl-8 mx-auto col-lg-7">
      <div class="card shadow mb-4">
          <div class="card">
              <div class="card-header">
                  <strong class="card-title">{{ title.upper }}</strong>
              </div>
              <div class="card-body">
              {%for notificationData in notificationData.all %}
                  <div class="sufee-alert alert with-close alert-{{ notificationData.priority }} alert-dismissible fade show">
                      <span class="badge badge-pill badge-{{ notificationData.priority }}">{{ notificationData.get_priority_display }}</span>
                      {{ notificationData.message }}
                      
                  </div>
              {% endfor %}
              
              </div>
          </div>
      </div>
    </div>
  </div>


{% endblock %}

templates/profile.html
{% extends 'blank.html' %}
{% load static %}
{% block content  %}
  <!-- Page Heading -->
  <div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">{{ title }}</h1>
    <a href="#" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i class="fab fa-chart fa-sm text-white-50"></i> Students Rating</a>
  </div>

  <!-- Content Row -->
  <div class="row">

    {% if request.user.is_authenticated %}
      <div style="display: {{displayProfileStyle}} " class="col-md-6 offset-md-3">
        <div class="card">
          <div class="card">
            <div class="card-header">
                <i class="fa fa-user"></i><strong class="card-title pl-2">{{title.upper}}</strong>
            </div>
            <div class="card-body">
                <div class="">
                    {% if profileData.displayImage_url %}
                      <img style="height:250px;" class="rounded-circle mx-auto d-block" src="{{ profileData.displayImage_url }}" alt="Profile Image">
                    {% else %}
                      <img class="img-profile mx-auto d-block rounded-circle" src="{% static 'img/favicon.png' %}" alt="">
                    {% endif %}
                    <h5 class="text-sm-center mt-2 mb-1">{{profileData.fullName.title}}({{profileData.displayName.title}})</h5>
                    <div class="location text-sm-center"><i class="fa fa-map-marker"></i> {{profileData.address.title}}, {{profileData.state.title}} {{profileData.country.title}}</div>
                    <div class="text-sm-center">
                      <p><strong>Role: </strong>{{profileData.role}}</p>
                      <p><strong>Department: </strong>{{profileData.department}}</p>
                      <p><strong>Class: </strong>{{profileData.grade}}</p>
                      <p><strong>Email: </strong>{{profileData.email}}</p>
                      <p><strong>Date Of Birth: </strong>{{profileData.dob}}</p>
                      <p><strong>Phone Number: </strong>{{profileData.phone}}</p>
                      <p><strong>Disability: </strong>{{profileData.disability}}</p>
                      <u><p><strong>Profile</strong></p></u>
                      <p>{{profileData.profile}}</p>
                    </div>

                </div>
                <hr>
                <div class="card-text text-sm-center">
                    <a href="#"><i class="fa fa-facebook pr-1"></i></a>
                </div>
            </div>
          </div>
        </div>
      </div>
      <div style="display: {{displayFormStyle}}" class="col-12">
        <div class="card">
          <div id="ProfileDetailForm">
            <form method="POST" name="ProfileForm" action="{% url 'core:ProfileFormValidator' %}" enctype="multipart/form-data" >
             {% csrf_token %}            
              <div class="card-header">
                  <strong>Profile</strong> <small> Fill in Your Details</small>
              </div>
              <div class="card-body card-block">
                  <div class="row form-group">
                    <div class="form-group col-md-3">
                      <label class=" form-control-label">Role</label>
                      <div class="input-group">
                          {{ profileData.role }}
                      </div>
                    </div>
                    <div class="form-group col-md-3">
                        <label class=" form-control-label">Department</label>
                        <div class="input-group">
                            {{ profileData.department }}
                        </div>
                    </div>
                    <div class="form-group col-md-3">
                        <label class=" form-control-label">Date of Birth</label>
                        <div class="input-group">
                            {{ profileData.dob }}
                        </div>
                        <small class="form-text text-muted">ex. 99/99/9999</small>
                    </div>
                    <div class="form-group col-md-3">
                        <label class=" form-control-label">Show Date</label>
                        <div class="input-group">
                            {{ profileData.showDOB }}
                        </div>
                    </div>
                  </div>

                  <div class="row form-group">
                    <div class="form-group col-md-3">
                        <label class=" form-control-label">Grade input</label>
                        <div class="input-group">
                            {{ profileData.grade }}
                        </div>
                        <small class="form-text text-muted">ex. 99/99/9999</small>
                    </div>
                    <div class="form-group col-md-3">
                        <label class=" form-control-label">FullName</label>
                        <div class="input-group">
                            {{ profileData.fullName }}
                        </div>
                        <small class="form-text text-muted">ex. John Doe</small>
                    </div>
                    <div class="form-group col-md-3">
                        <label class=" form-control-label">Phone input</label>
                        <div class="input-group">
                            {{ profileData.phone }}
                        </div>
                        <small class="form-text text-muted">+234 **** *** ****</small>
                    </div>
                    <div class="form-group col-md-3">
                      <label class=" form-control-label">Show Phone To Others</label>
                        <div class="input-group">
                            {{ profileData.showPhone }}
                        </div>
                    </div>
                  </div>

                  <div class="row form-group">
                    <div class="form-group col-md-4">
                        <label class=" form-control-label">Address input</label>
                        <div class="input-group">
                            {{ profileData.address }}
                        </div>
                        <small class="form-text text-muted">ex. 19, Mushin street, Mushin</small>
                    </div>
                    <div class="form-group col-md-4">
                        <label class=" form-control-label">State input</label>
                        <div class="input-group">
                            {{ profileData.state }}
                        </div>
                        <small class="form-text text-muted">ex. Lagos</small>
                    </div>
                    <div class="form-group col-md-4">
                        <label class=" form-control-label">Country input</label>
                        <div class="input-group">
                            {{ profileData.country }}
                        </div>
                        <small class="form-text text-muted">ex. Nigeria</small>
                    </div>
                  </div>
                  
                  <div class="row form-group">
                    <div class="form-group col-md-6">
                        <label class=" form-control-label">Disability</label>
                        <div class="input-group">
                            {{ profileData.disability }}
                        </div>
                        <small class="form-text text-muted">ex. None/Deaf/Dumb</small>
                    </div>
                    <div class="form-group col-md-6">
                        <label class=" form-control-label">Email</label>
                        <div class="input-group">
                            {{ profileData.email }}
                        </div>
                        <small class="form-text text-muted">ex. Johndoe@email.com</small>
                    </div>
                  </div>

                  <div class="form-group">
                      <label class=" form-control-label">Brief Description Of Your Self</label>
                      <div class="input-group">
                          {{ profileData.profile }}
                      </div>
                      <small class="form-text text-muted">Not more than 50 Words</small>
                  </div>
                  <button type="submit" class="btn btn-primary btn-block">Create</button>
              </div>
            </form>
          </div>
        </div>
      </div>
    {% endif %}
   </div>


{% endblock %}

templates/report-bug.html
{% extends 'blank.html' %}
{% load static %}
{% block content  %}
{% load crispy_forms_tags %}

  <!-- Page Heading -->
  <div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">{{ title }}</h1>
    <a href="#" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i class="fab fa-chart fa-sm text-white-50"></i> Students Rating</a>
  </div>
  <!-- Content Row -->

  <div class="row">

    <!-- Content -->
    <div class="col-xl-8 mx-auto col-lg-7">
      <div class="card shadow mb-4">
        <form method="post"  class="m-5" action="{% url 'core:addBugsForm' %}">
          {% csrf_token %}
          {{ bugsForm | crispy }}
          <button class="btn btn-block btn-primary" type="submit">Create</button>
        </form>
      </div>
    </div>
  </div>

  <script type="text/javascript">
            userInputField = document.getElementById('id_user')
            userInputField.value = '{{ request.user }}'
            userInputField.style.display = 'none'
            document.getElementById('div_id_user').style.display = 'none'
  </script>

{% endblock %}

templates/view-class.html
{% extends 'blank.html' %}
{% load static %}
{% block content  %}
  <!-- Page Heading -->
  <div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">{{ title }}</h1>
    <a href="#" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i class="fab fa-chart fa-sm text-white-50"></i> Students Rating</a>
  </div>

  <!-- Content Row -->
  <div class="row"> 
    <div class="col-md-12">      
      <div class="card">
        <div class="card-header">
          <i class="fa fa-book"></i>
          <strong class="card-title">{{ content.topic }}</strong>
        </div>
        <div class="card-body">
          <p><strong>Subject:</strong> {{ content.subject }}</p>
          <p><strong>Teacher:</strong> {{ content.teacher_name }}</p>
          <h3 class="mx-auto"><u><center><strong>Content:</strong></center></u></h3>
          <p>{{ content.content }}</p>
          {% if content.material %}
            <a target="_blank" href="{{ content.material.url }}">Download Material</a>
          {% endif %}
          
        </div>
      </div>
    </div>  
  </div>


{% endblock %}